### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by KeyWeeUsr** [nskrypnik/kivy3#11]
Please add a LICENSE file with a license this repo is under, so that it's easier to work with if included in some project.

Get inspired [here](https://opensource.org/licenses/) and how to add it the simple/github way [here](https://help.github.com/articles/open-source-licensing/#how-can-i-go-back-through-my-public-repositories-and-give-them-licenses).

**Comment by nskrypnik** [comment]
https://github.com/nskrypnik/kivy3/commit/251f60bf4a6361bbe533dd14747cffff658a02d1 - here you go. Thank you for noticing.
